{
 "title": "Vector",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "host", "label": "Host", "query": { "query": "label_values(host)" } },
   { "name": "pid", "label": "pid", "query": { "query": "label_values(pid)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "component_id", "label": "Component id", "query": { "query": "label_values(component_id)" } },
   { "name": "component_type", "label": "Component type", "query": { "query": "label_values(component_type)" } },
   { "name": "component_kind", "label": "Component kind", "query": { "query": "label_values(component_kind)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilization",
     "type": "timeseries",
     "description": "A ratio from 0 to 1 of the load on a component. A value of 0 would indicate a completely idle component that is simply waiting for input. A value of 1 would indicate a that is never idle. This value is updated every 5 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "vector_utilization { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processed bytes rate",
     "type": "timeseries",
     "description": "The rate of bytes processed by the component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "rate(vector_processed_bytes_total{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Component sent events rate",
     "type": "timeseries",
     "description": "The rate of events emitted by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(vector_component_sent_events_total{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Component sent event bytes rate",
     "type": "timeseries",
     "description": "The rate of event bytes emitted by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "rate(vector_component_sent_event_bytes_total{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\" }[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Component sent bytes rate",
     "type": "timeseries",
     "description": "The rate of raw bytes sent by this component to destination sinks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(vector_component_sent_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Component received bytes rate",
     "type": "timeseries",
     "description": "The rate of raw bytes accepted by this component from source origins.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(vector_component_received_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Component received events rate",
     "type": "timeseries",
     "description": "The rate of events accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "rate(vector_component_received_events_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Component received event bytes rate",
     "type": "timeseries",
     "description": "The rate of event bytes accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "rate(vector_component_received_event_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Component received events count",
     "type": "timeseries",
     "description": "A histogram of the number of events passed in each internal batch in Vector’s internal topology.\n\nNote that this is separate than sink-level batching. It is mostly useful for low level debugging performance issues in Vector due to small internal batches.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "vector_component_received_events_count{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Component discarded events rate",
     "type": "timeseries",
     "description": "The rate of events dropped by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "rate(vector_component_discarded_events_total{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Started total",
     "type": "timeseries",
     "description": "The total number of times the Vector instance has been started.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "vector_api_started_total{ host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stopped total",
     "type": "timeseries",
     "description": "The total number of times the Vector instance has been stopped.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "vector_stopped_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quit total",
     "type": "timeseries",
     "description": "The total number of times the Vector instance has quit.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "vector_quit_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reloaded total",
     "type": "timeseries",
     "description": "The total number of times the Vector instance has been reloaded.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "vector_reloaded_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API started total",
     "type": "timeseries",
     "description": "The number of times the Vector GraphQL API has been started.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "vector_api_started_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Value limit reached rate",
     "type": "timeseries",
     "description": "The rate of times new values for a key have been rejected because the value limit has been reached.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "rate(vector_value_limit_reached_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection failed total",
     "type": "timeseries",
     "description": "The total number of times a connection has failed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "vector_connection_failed_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection send ack errors total",
     "type": "timeseries",
     "description": "The total number of protocol acknowledgement errors for this Vector instance for source protocols that support acknowledgements.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "targets": [
      {
       "expr": "vector_connection_send_ack_errors_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection errors total",
     "type": "timeseries",
     "description": "The total number of connection errors for this Vector instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "vector_connection_errors_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UTF-8 convert errors rate",
     "type": "timeseries",
     "description": "The rate of errors converting bytes to a UTF-8 string in UDP mode.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "rate(vector_utf8_convert_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Timestamp parse errors rate",
     "type": "timeseries",
     "description": "The rate of errors encountered parsing RFC 3339 timestamps.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "rate(vector_timestamp_parse_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Checksum errors rate",
     "type": "timeseries",
     "description": "The rate of errors identifying files via checksum.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "vector_checksum_errors_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stdin reads failed rate",
     "type": "timeseries",
     "description": "The rate of errors reading from stdin.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "rate(vector_stdin_reads_failed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Component errors rate",
     "type": "timeseries",
     "description": "The rate of errors encountered by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "rate(vector_component_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reload errors rate",
     "type": "timeseries",
     "description": "The rate of errors encountered when reloading Vector.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "rate(vector_reload_errors_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Recover errors rate",
     "type": "timeseries",
     "description": "The rate of errors caused by Vector failing to recover from a failed reload.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "expr": "rate(vector_recover_errors_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Protobuf decode errors rate",
     "type": "timeseries",
     "description": "The rate of Protocol Buffers errors thrown during communication between Vector instances.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "rate(vector_protobuf_decode_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection read errors rate",
     "type": "timeseries",
     "description": "The rate of errors reading datagram.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "rate(vector_connection_read_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logging driver errors rate",
     "type": "timeseries",
     "description": "The rate of logging driver errors encountered caused by not using either the jsonfile or journald driver.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "rate(vector_logging_driver_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Communication errors rate",
     "type": "timeseries",
     "description": "The rate of errors stemming from communication with the Docker daemon.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "targets": [
      {
       "expr": "rate(vector_communication_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Encode errors rate",
     "type": "timeseries",
     "description": "The rate of errors encountered when encoding an event.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "rate(vector_encode_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Decode errors rate",
     "type": "timeseries",
     "description": "The rate of decode errors seen when decoding data in a source component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "targets": [
      {
       "expr": "rate(vector_decode_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parse errors rate",
     "type": "timeseries",
     "description": "The rate of errors parsing metrics for this component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
     "targets": [
      {
       "expr": "rate(vector_parse_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Config load errors rate",
     "type": "timeseries",
     "description": "The rate of errors loading the Vector configuration.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
     "targets": [
      {
       "expr": "rate(vector_config_load_errors_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\"})[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection send errors rate",
     "type": "timeseries",
     "description": "The rate of errors sending data via the connection.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
     "targets": [
      {
       "expr": "rate(vector_connection_send_errors_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lua memory used bytes",
     "type": "timeseries",
     "description": "The total memory currently being used by the Lua runtime.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
     "targets": [
      {
       "expr": "vector_lua_memory_used_bytes { host =~ \"$host\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Command executed rate",
     "type": "timeseries",
     "description": "The rate of times a command has been executed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "rate(vector_command_executed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Command execution duration seconds",
     "type": "timeseries",
     "description": "The command execution duration in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "targets": [
      {
       "expr": "vector_command_execution_duration_seconds { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Collect completed rate",
     "type": "timeseries",
     "description": "The rate of metrics collections completed for this component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "targets": [
      {
       "expr": "rate(vector_collect_completed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Collect duration seconds",
     "type": "timeseries",
     "description": "The duration spent collecting of metrics for this component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
     "targets": [
      {
       "expr": "vector_collect_duration_seconds { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Tag value limit exceeded rate",
     "type": "timeseries",
     "description": "The rate of events discarded because the tag has been rejected after hitting the configured value_limit.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "targets": [
      {
       "expr": "rate(vector_tag_value_limit_exceeded_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Checkpoints total",
     "type": "timeseries",
     "description": "The total number of files checkpointed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
     "targets": [
      { "expr": "vector_checkpoints_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Streams total",
     "type": "timeseries",
     "description": "The total number of streams.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
     "targets": [
      { "expr": "vector_streams_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Connection shutdown rate",
     "type": "timeseries",
     "description": "The rate of times the connection has been shut down.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
     "targets": [
      {
       "expr": "rate(vector_connection_shutdown_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stale events flushed rate",
     "type": "timeseries",
     "description": "The rate of stale events that Vector has flushed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
     "targets": [
      {
       "expr": "rate(vector_stale_events_flushed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "description": "The total number of seconds the Vector instance has been up.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
     "targets": [
      {
       "expr": "vector_uptime_seconds{host =~ \"$host\", job =~ \"$job\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Invalid record rate",
     "type": "timeseries",
     "description": "The rate of invalid records that have been discarded.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "targets": [
      {
       "expr": "rate(vector_invalid_record_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Invalid record bytes rate",
     "type": "timeseries",
     "description": "The rate of bytes from invalid records that have been discarded.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "targets": [
      {
       "expr": "rate(vector_invalid_record_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Open connections",
     "type": "timeseries",
     "description": "The number of current open connections to Vector.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "targets": [
      {
       "expr": "vector_open_connections { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connection established rate",
     "type": "timeseries",
     "description": "The rate of times a connection has been established.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "targets": [
      {
       "expr": "rate(vector_connection_established_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lag time seconds",
     "type": "timeseries",
     "description": "The difference between the timestamp recorded in each event and the time when it was ingested, expressed as fractional seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "targets": [
      {
       "expr": "vector_lag_time_seconds { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Internal metrics cardinality",
     "type": "timeseries",
     "description": "The total number of metrics emitted from the internal metrics registry.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "targets": [
      {
       "expr": "vector_internal_metrics_cardinality",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Events discarded rate",
     "type": "timeseries",
     "description": "The rate of events discarded by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "targets": [
      {
       "expr": "rate(vector_events_discarded_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "AWS EC2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metadata refresh successful rate",
     "type": "timeseries",
     "description": "The rate of AWS EC2 metadata refreshes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(vector_metadata_refresh_successful_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metadata refresh failed rate",
     "type": "timeseries",
     "description": "The rate of failed efforts to refresh AWS EC2 metadata.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "rate(vector_metadata_refresh_failed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events recorded rate",
     "type": "timeseries",
     "description": "The rate of events recorded by the aggregate transform.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(vector_aggregate_events_recorded_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Flushes rate",
     "type": "timeseries",
     "description": "The rate of flushes done by the aggregate transform.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "rate(vector_aggregate_flushes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed updates rate",
     "type": "timeseries",
     "description": "The rate of failed metric updates, incremental adds, encountered by the aggregate transform.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(vector_aggregate_failed_updates { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Adaptive concurrency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Observed RTT",
     "type": "timeseries",
     "description": "The observed round-trip time (RTT) for requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "vector_adaptive_concurrency_observed_rtt { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Averaged RTT",
     "type": "timeseries",
     "description": "The average round-trip time (RTT) for the current window.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "vector_adaptive_concurrency_averaged_rtt { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Limit",
     "type": "timeseries",
     "description": "The concurrency limit that the adaptive concurrency feature has decided on for this current window.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "vector_adaptive_concurrency_limit { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "In flight",
     "type": "timeseries",
     "description": "The number of outbound requests currently awaiting a response.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "vector_adaptive_concurrency_in_flight { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sent events rate",
     "type": "timeseries",
     "description": "The rate of events sent by this buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "rate(vector_buffer_sent_events_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sent event bytes rate",
     "type": "timeseries",
     "description": "The rate of bytes sent by this buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "rate(vector_buffer_sent_event_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received events rate",
     "type": "timeseries",
     "description": "The rate of events received by this buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(vector_buffer_received_events_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received bytes rate",
     "type": "timeseries",
     "description": "The rate of bytes received by this buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "rate(vector_buffer_received_event_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Events",
     "type": "timeseries",
     "description": "The number of events currently in the buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "vector_buffer_events { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Byte size",
     "type": "timeseries",
     "description": "The number of bytes current in the buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "vector_buffer_byte_size { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Discarded events rate",
     "type": "timeseries",
     "description": "The rate of events dropped by this non-blocking buffer.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "rate(vector_buffer_discarded_events_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Watched rate",
     "type": "timeseries",
     "description": "The rate of times Vector started watching for container logs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rate(vector_containers_watched_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unwatched rate",
     "type": "timeseries",
     "description": "The rate of times Vector stopped watching for container logs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "rate(vector_containers_unwatched_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processed events rate",
     "type": "timeseries",
     "description": "The rate of container events processed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "rate(vector_container_processed_events_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metadata fetch errors rate",
     "type": "timeseries",
     "description": "The rate of errors encountered when fetching container metadata.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "rate(vector_container_metadata_fetch_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Datadog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs received rate",
     "type": "timeseries",
     "description": "Rate of Datadog logs received.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(vector_datadog_logs_received_in_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metrics received rate",
     "type": "timeseries",
     "description": "Rate of Datadog metrics received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "rate(vector_datadog_metrics_received_in_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Added rate",
     "type": "timeseries",
     "description": "The rate of files Vector has found to watch.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(vector_files_added_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Resumed rate",
     "type": "timeseries",
     "description": "The rate of times Vector has resumed watching a file.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "rate(vector_files_resumed_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unwatched rate",
     "type": "timeseries",
     "description": "The rate of times Vector has stopped watching a file.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "rate(vector_files_unwatched_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Deleted rate",
     "type": "timeseries",
     "description": "The rate of files deleted.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "rate(vector_files_deleted_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests rate",
     "type": "timeseries",
     "description": "The rate of HTTP requests issued by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(vector_http_requests_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request errors rate",
     "type": "timeseries",
     "description": "The rate of HTTP request errors for this component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "rate(vector_http_request_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client responses rate",
     "type": "timeseries",
     "description": "The rate of HTTP requests, tagged with the response code.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(vector_http_client_responses_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error response rate",
     "type": "timeseries",
     "description": "The rate of HTTP error responses for this component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(vector_http_error_response_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client RTT seconds",
     "type": "timeseries",
     "description": "The round-trip time (RTT) of HTTP requests.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "vector_http_client_rtt_seconds { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client response RTT seconds",
     "type": "timeseries",
     "description": "The round-trip time (RTT) of HTTP requests, tagged with the response code.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "vector_http_client_response_rtt_seconds { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bad requests rate",
     "type": "timeseries",
     "description": "The total number of HTTP 400 Bad Request errors encountered.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "rate(vector_http_bad_requests_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests rate",
     "type": "timeseries",
     "description": "The rate of requests sent to Kafka brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(vector_kafka_requests_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests bytes rate",
     "type": "timeseries",
     "description": "The rate of bytes transmitted to Kafka brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "rate(vector_kafka_requests_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Responses rate",
     "type": "timeseries",
     "description": "The rate of responses received from Kafka brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(vector_kafka_responses_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Responses bytes rate",
     "type": "timeseries",
     "description": "The rate of bytes received from Kafka brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "rate(vector_kafka_responses_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Produced messages rate",
     "type": "timeseries",
     "description": "Rate of messages transmitted (produced) to Kafka brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "rate(vector_kafka_produced_messages_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Produced messages bytes rate",
     "type": "timeseries",
     "description": "Rate of message bytes (including framing, such as per-Message framing and MessageSet/batch framing) transmitted to Kafka brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(vector_kafka_produced_messages_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consumed messages rate",
     "type": "timeseries",
     "description": "Rate of messages consumed, not including ignored messages (due to offset, etc), from Kafka brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(vector_kafka_consumed_messages_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consumed messages bytes rate",
     "type": "timeseries",
     "description": "Rate of message bytes (including framing) received from Kafka brokers.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "rate(vector_kafka_consumed_messages_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Messages queue",
     "type": "timeseries",
     "description": "Current number of messages in producer queues.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "vector_kafka_queue_messages { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Queue messages bytes",
     "type": "timeseries",
     "description": "Current total size of messages in producer queues.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "vector_kafka_queue_messages_bytes { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Events failed rate",
     "type": "timeseries",
     "description": "The rate of failures to read a Kafka message.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(vector_events_failed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consumer offset updates failed rate",
     "type": "timeseries",
     "description": "The rate of failures to update a Kafka consumer offset.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "rate(vector_consumer_offset_updates_failed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Watch requests invoked rate",
     "type": "timeseries",
     "description": "The rate of watch requests invoked.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(vector_k8s_watch_requests_invoked_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Watch requests failed rate",
     "type": "timeseries",
     "description": "The rate of watch requests failed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "rate(vector_k8s_watch_requests_failed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Watch stream items obtained rate",
     "type": "timeseries",
     "description": "The rate of items obtained from a watch stream.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rate(vector_k8s_watch_stream_items_obtained_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Watch stream failed rate",
     "type": "timeseries",
     "description": "The rate of watch streams failed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "rate(vector_k8s_watch_stream_failed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Watcher HTTP error rate",
     "type": "timeseries",
     "description": "The rate of HTTP error responses for the Kubernetes watcher.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(vector_k8s_watcher_http_error_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event annotation failures rate",
     "type": "timeseries",
     "description": "The rate of failures to annotate Vector events with Kubernetes Pod metadata.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "rate(vector_k8s_event_annotation_failures_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stream chunks processed rate",
     "type": "timeseries",
     "description": "The rate of chunks processed from the stream of Kubernetes resources.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "rate(vector_k8s_stream_chunks_processed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stream processed bytes rate",
     "type": "timeseries",
     "description": "The rate of bytes processed from the stream of Kubernetes resources.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "rate(vector_k8s_stream_processed_bytes_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Format picker edge cases rate",
     "type": "timeseries",
     "description": "The rate of edge cases encountered while picking format of the Kubernetes log message.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(vector_k8s_format_picker_edge_cases_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reflector desyncs rate",
     "type": "timeseries",
     "description": "The rate of desyncs for the reflector.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "rate(vector_k8s_reflector_desyncs_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Docker format parse failures rate",
     "type": "timeseries",
     "description": "The rate of failures to parse a message as a JSON object.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(vector_k8s_docker_format_parse_failures_total{ component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "State ops rate",
     "type": "timeseries",
     "description": "The rate of state operations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "rate(vector_k8s_state_ops_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received rate",
     "type": "timeseries",
     "description": "The rate of requests received by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "rate(vector_requests_received_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Completed rate",
     "type": "timeseries",
     "description": "The rate of requests completed by this component.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "rate(vector_requests_completed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read errors rate",
     "type": "timeseries",
     "description": "The rate of request read errors for this component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rate(vector_request_read_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Send errors rate",
     "type": "timeseries",
     "description": "The rate of errors sending messages.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "rate(vector_send_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors rate",
     "type": "timeseries",
     "description": "The rate of requests errors for this component.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "rate(vector_request_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Automatic decode errors rate",
     "type": "timeseries",
     "description": "The rate of request errors for this component when it attempted to automatically discover and handle the content-encoding of incoming request data.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "rate(vector_request_automatic_decode_errors_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Duraton seconds",
     "type": "timeseries",
     "description": "The total request duration in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "vector_request_duration_seconds { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Splunk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending acks",
     "type": "timeseries",
     "description": "The number of outstanding Splunk HEC indexer acknowledgement acks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "vector_splunk_pending_acks { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" }",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SQS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message received messages rate",
     "type": "timeseries",
     "description": "The rate of received SQS messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "rate(vector_sqs_message_received_messages_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message receive succeded rate",
     "type": "timeseries",
     "description": "The rate of times successfully receiving SQS messages.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "rate(vector_sqs_message_receive_succeeded_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message processing succeded rate",
     "type": "timeseries",
     "description": "The rate of SQS messages successfully processed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "rate(vector_sqs_message_processing_succeeded_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message delete succeeded rate",
     "type": "timeseries",
     "description": "The rate of successful deletions of SQS messages.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "rate(vector_sqs_message_delete_succeeded_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "S3 event record ignored rate",
     "type": "timeseries",
     "description": "The rate of times an S3 record in an SQS message was ignored (for an event that was not ObjectCreated).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "rate(vector_sqs_s3_event_record_ignored_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message delete failed rate",
     "type": "timeseries",
     "description": "The rate of failures to delete SQS messages.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "rate(vector_sqs_message_delete_failed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message receive failed rate",
     "type": "timeseries",
     "description": "The rate of failures to receive SQS messages.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "rate(vector_sqs_message_receive_failed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message processing failed rate",
     "type": "timeseries",
     "description": "The rate of failures to process SQS messages.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "rate(vector_sqs_message_processing_failed_total { component_id =~ \"$component_id\", component_type =~ \"$component_type\", component_kind =~ \"$component_kind\", host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Windows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service start rate",
     "type": "timeseries",
     "description": "The rate of times the Windows service has been started.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "rate(vector_windows_service_start_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service stop rate",
     "type": "timeseries",
     "description": "The rate of times the Windows service has been stopped.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "rate(vector_windows_service_stop_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service restart rate",
     "type": "timeseries",
     "description": "The rate of times the Windows service has been restarted.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "rate(vector_windows_service_restart_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service does not exist rate",
     "type": "timeseries",
     "description": "The rate of errors raised due to the Windows service not existing.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "rate(vector_windows_service_does_not_exist_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service install rate",
     "type": "timeseries",
     "description": "The rate of times the Windows service has been installed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "rate(vector_windows_service_install_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service uninstall rate",
     "type": "timeseries",
     "description": "The rate of times the Windows service has been uninstalled.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "rate(vector_windows_service_uninstall_total { host =~ \"$host\", pid =~ \"$pid\", job =~ \"$job\", instance =~ \"$instance\" })[$__rate_interval]",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}